### ISSUE TITLE
Installation - ValueError: 'coord_update.pyx' doesn't match any files

### ISSUE THREAD

**Issue by akilat90** [flatironinstitute/online_psp#11]
I'm trying to install the package by appending the parent directory of `online_psp` to `PYTHONPATH` and running `python setup.py build_ext --inplace`

I'm getting the below error:

    Traceback (most recent call last):
      File "setup.py", line 13, in <module>
        ext_modules=cythonize("coord_update.pyx"),
      File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 818, in cythonize
    aliases=aliases)
      File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 704, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 108, in nonempty
        raise ValueError(error_msg)
    ValueError: 'coord_update.pyx' doesn't match any files

Env: Ubuntu 16.04 container on a Windows 10 host.

**Comment by victorminden** [comment]
Reproduced on Mac, I pushed what I believe is a fix -- seems that the path in setup.py still points to coord_update.pyx and not to online_psp/coord_update.pyx . Can you try pulling and running again?

**Comment by akilat90** [comment]
Thanks! Successfully installed this time.
